# Generated by Django 6.0.6 on 2026-08-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento'), ('Dañado', 'Dañado')], default='Disponible', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sede')),
            ],
        ),
    ]
