# Generated by Django 6.0.6 on 2026-08-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad_danada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_mantenimiento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_prestada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
