# Generated by Django 6.0.6 on 2026-08-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestada', 'Prestada'), ('Mantenimiento', 'Mantenimiento'), ('Dañada', 'Dañada')], default='Disponible', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
        ),
    ]
