# Generated by Django 6.0.6 on 2026-08-19 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_cantidad_danada_and_more'),
        ('solicitudes_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_equipo', to='inventario.inventario'),
        ),
    ]
