# Generated by Django 6.0.6 on 2026-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_equipos', '0002_alter_solicitudequipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudequipo',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
