# Generated by Django 6.0.6 on 2026-08-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=150)),
                ('carrera', models.CharField(max_length=150)),
                ('profesor', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='permisos_herramientas/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Devuelta', 'Devuelta')], default='Pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.herramienta')),
            ],
        ),
    ]
