# Generated by Django 6.0.6 on 2026-08-06 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Superadministrador', 'Superadministrador'), ('Administrador Talleres', 'Administrador de Talleres o Laboratorio'), ('Coordinador Carrera', 'Coordinador de Carrera'), ('Coordinador Talleres', 'Coordinador de Talleres y Laboratorio'), ('Docente', 'Docente'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=50)),
                ('descripcion', models.CharField(blank=True, help_text='Observaciones o cargo adicional del usuario.', max_length=250)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carreras.carrera')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.sede')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
